
spring:
  mail:
    host: smtp.qq.com
    username: he.legend@qq.com
    password: bclyphkbrcbybadi
    port: 587
    default-encoding: utf-8
    properties:
      from: 1603020074@qq.com
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:h2:file:/data/assistant-lottery
    username: assistant
    password: lottery
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 7000
